CREATE TABLE NM_ROLE(
ID BINARY(16) PRIMARY KEY NOT NULL,
NAME VARCHAR(40)
)ENGINE=INNODB;

INSERT INTO NM_ROLE (ID, NAME) VALUES (UNHEX(REPLACE(UUID(), '-', '')), 'ADMINGERAL');
INSERT INTO NM_ROLE (ID, NAME) VALUES (UNHEX(REPLACE(UUID(), '-', '')), 'ADMINCONDOMINIO');
INSERT INTO NM_ROLE (ID, NAME) VALUES (UNHEX(REPLACE(UUID(), '-', '')), 'USUARIOCONDOMINIO');
INSERT INTO NM_ROLE (ID, NAME) VALUES (UNHEX(REPLACE(UUID(), '-', '')), 'PERFILMORADOR');

