CREATE TABLE NM_USUARIO_ROLE(
    ID BINARY(16) NOT NULL,
    ROLE_ID BINARY(16) NOT NULL,
    CONSTRAINT FK_USUARIO_ROLE FOREIGN KEY(ID) REFERENCES NM_USUARIO(ID),
    CONSTRAINT FK_ROLE_ID FOREIGN KEY(ROLE_ID) REFERENCES NM_ROLE(ID)
)ENGINE=INNODB;

