CREATE TABLE IF NOT EXISTS NM_CONDOMINIO
(
    ID BINARY(16) PRIMARY KEY NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    CNPJ VARCHAR(20),
    TELEFONE VARCHAR(16),
    EMAIL VARCHAR(80),
    CEP VARCHAR(10) NOT NULL,
    LOGRADOURO VARCHAR(80) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR(30),
    BAIRRO VARCHAR(80) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(40) NOT NULL,
    DATA_CADASTRO DATETIME NOT NULL,
    TIPO VARCHAR(1) NOT NULL,
    IND_GERA_COBRANCA VARCHAR(1) NOT NULL DEFAULT 'S'
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
