CREATE TABLE IF NOT EXISTS NM_CONDOMINIO
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    CNPJ VARCHAR(20),
    TELEFONE VARCHAR(16),
    EMAIL VARCHAR(80),
    CEP VARCHAR(10),
    LOGRADOURO VARCHAR(80),
    NUMERO VARCHAR(10),
    COMPLEMENTO VARCHAR(30),
    BAIRRO VARCHAR(80),
    CIDADE VARCHAR(100),
    ESTADO VARCHAR(40),
    DATA_CADASTRO DATETIME,
    TIPO VARCHAR(1),
    IND_GERA_COBRANCA VARCHAR(1) NOT NULL DEFAULT 'S'
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
