CREATE TABLE IF NOT EXISTS NM_CONDOMINIO
(
    ID BINARY(16) PRIMARY KEY NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    CNPJ VARCHAR(20),
    TELEFONE VARCHAR(16),
    EMAIL VARCHAR(80),
    CEP VARCHAR(10) NOT NULL,
    LOGRADOURO VARCHAR(80) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR(30),
    BAIRRO VARCHAR(80) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    ESTADO VARCHAR(40) NOT NULL,
    STATUS INTEGER,
    DATA_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_ALTERACAO DATE
)ENGINE=INNODB;
