CREATE TABLE NM_USUARIO_CONDOMINIO(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    USUARIO_ID BIGINT NOT NULL,
    CONDOMINIO_ID BIGINT NOT NULL,
 CONSTRAINT FK_USUARIO_CONDOMINIO_USUARIO FOREIGN KEY(USUARIO_ID) REFERENCES NM_USUARIO(ID),
 CONSTRAINT FK_USUARIO_CONDOMINIO_CONDOMINIO FOREIGN KEY(CONDOMINIO_ID) REFERENCES NM_CONDOMINIO(ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
