CREATE TABLE NM_USUARIO_CONDOMINIO(
    ID BINARY(16) PRIMARY KEY NOT NULL,
    USUARIO_ID BINARY(16) NOT NULL,
    CONDOMINIO_ID BINARY(16) NOT NULL,
 CONSTRAINT FK_USUARIO_CONDOMINIO_USUARIO FOREIGN KEY(USUARIO_ID) REFERENCES NM_USUARIO(ID),
 CONSTRAINT FK_USUARIO_CONDOMINIO_CONDOMINIO FOREIGN KEY(CONDOMINIO_ID) REFERENCES NM_CONDOMINIO(ID)
)ENGINE=INNODB;
