CREATE TABLE IF NOT EXISTS NM_UNIDADE(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CONDOMINIO_ID BIGINT NOT NULL,
    DESCRICAO BIGINT NOT NULL,
    CONSTRAINT FK_UNIDADE_CONDOMINIO FOREIGN KEY (CONDOMINIO_ID) REFERENCES NM_CONDOMINIO (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;