CREATE TABLE IF NOT EXISTS NM_UNIDADE(
    ID BINARY(16) PRIMARY KEY NOT NULL,
    CONDOMINIO_ID BINARY(16) NOT NULL,
    DESCRICAO VARCHAR(60) NOT NULL,
    CONSTRAINT FK_UNIDADE_CONDOMINIO FOREIGN KEY (CONDOMINIO_ID) REFERENCES NM_CONDOMINIO (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;