CREATE TABLE IF NOT EXISTS NM_CONDOMINO(
    ID BINARY(16) PRIMARY KEY NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    TELEFONE VARCHAR(16) NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,
    UNIDADE_ID BINARY(16)  NOT NULL,
    CONSTRAINT FK_UNIDADE_CONDOMINO FOREIGN KEY (UNIDADE_ID) REFERENCES NM_UNIDADE(ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;