CREATE TABLE IF NOT EXISTS NM_METODO_PAGAMENTO(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DESCRICAO VARCHAR(50) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;