CREATE TABLE IF NOT EXISTS NM_ASSINATURA(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CONDOMINIO_ID BIGINT NOT NULL,
    TIPO_COBRANCA_ID BIGINT NOT NULL,
    METODO_PAGAMENTO_ID BIGINT NOT NULL,
    DATA_ASSINATURA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_INICIO_COBRANCA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DIA_VENCIMENTO INT NOT NULL,
    VALOR DECIMAL(8,2) NOT NULL,
    DATA_CANCELAMENTO date DEFAULT NULL,
    DATA_PROX_VENCIMENTO date DEFAULT NULL,
    CONSTRAINT FK_ASSINATURA_CONDOMINIO FOREIGN KEY (CONDOMINIO_ID) REFERENCES NM_CONDOMINIO(ID),
    CONSTRAINT FK_ASSINATURA_TIPO_COBRANCA FOREIGN KEY (TIPO_COBRANCA_ID) REFERENCES NM_TIPO_COBRANCA(ID),
    CONSTRAINT FK_ASSINATURA_METODO_PAGAMENTO FOREIGN KEY (METODO_PAGAMENTO_ID) REFERENCES NM_METODO_PAGAMENTO(ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;