CREATE TABLE IF NOT EXISTS NM_ASSINATURA(
    ID BINARY(16) PRIMARY KEY NOT NULL,
    CONDOMINIO_ID BINARY(16) NOT NULL,
    TIPO_COBRANCA_ID BINARY(16) NOT NULL,
    METODO_PAGAMENTO_ID BINARY(16) NOT NULL,
    DATA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_INICIO_COBRANCA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DIA_VENCIMENTO INT NOT NULL,
    STATUS INTEGER NOT NULL,
    VALOR DECIMAL(8,2) NOT NULL,
    CONSTRAINT FK_ASSINATURA_CONDOMINIO FOREIGN KEY (CONDOMINIO_ID) REFERENCES NM_CONDOMINIO(ID),
    CONSTRAINT FK_ASSINATURA_TIPO_COBRANCA FOREIGN KEY (TIPO_COBRANCA_ID) REFERENCES NM_TIPO_COBRANCA(ID),
    CONSTRAINT FK_ASSINATURA_METODO_PAGAMENTO FOREIGN KEY (METODO_PAGAMENTO_ID) REFERENCES NM_METODO_PAGAMENTO(ID)
)ENGINE=INNODB;