CREATE TABLE NM_FATURA (
  ID binary(16) NOT NULL,
  ASSINATURA_ID binary(16) NOT NULL,
  DATA_LANCAMENTO date NOT NULL,
  DATA_VENCIMENTO date NOT NULL,
  VALOR_A_PAGAR decimal(8,2) NOT NULL,
  VALOR_DESCONTO decimal(8,2) DEFAULT NULL,
  DATA_PAGAMENTO date DEFAULT NULL,
  VALOR_PAGO decimal(8,2) DEFAULT NULL,
  OBSERVACAO varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY FK_ASSINATUFA_FATURA (ASSINATURA_ID),
  CONSTRAINT FK_ASSINATUFA_FATURA FOREIGN KEY (ASSINATURA_ID) REFERENCES NM_ASSINATURA (ID)
) ENGINE=InnoDB;