CREATE TABLE NM_FATURA (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  ASSINATURA_ID BIGINT NOT NULL,
  DATA_LANCAMENTO date NOT NULL,
  DATA_VENCIMENTO date NOT NULL,
  VALOR_A_PAGAR decimal(8,2) NOT NULL,
  VALOR_DESCONTO decimal(8,2) DEFAULT NULL,
  DATA_PAGAMENTO date DEFAULT NULL,
  VALOR_PAGO decimal(8,2) DEFAULT NULL,
  OBSERVACAO varchar(255) DEFAULT NULL,
  KEY FK_ASSINATUFA_FATURA (ASSINATURA_ID),
  CONSTRAINT FK_ASSINATUFA_FATURA FOREIGN KEY (ASSINATURA_ID) REFERENCES NM_ASSINATURA (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;