CREATE TABLE IF NOT EXISTS NM_ITEM_ASSINATURA(
    ID BINARY(16) PRIMARY KEY NOT NULL,
    ASSINATURA_ID BINARY(16) NOT NULL,
    DATA_LANCAMENTO TIMESTAMP NOT NULL,
    DATA_VENCIMENTO TIMESTAMP NOT NULL,
    DATA_PAGAMENTO TIMESTAMP NOT NULL,
    VALOR_DESCONTO DECIMAL(8,2) NOT NULL,
    VALOR_PAGO DECIMAL(8,2) NOT NULL,
    CONSTRAINT FK_ITEM_ASSINATURA_ASSINATURA FOREIGN KEY (ASSINATURA_ID) REFERENCES NM_ASSINATURA(ID)
)ENGINE=INNODB;