CREATE TABLE IF NOT EXISTS NM_NIVEL_COBRANCA(
    ID BINARY(16) PRIMARY KEY NOT NULL,
    LIMITE_INICIAL INT NOT NULL,
    LIMITE_FINAL INT NOT NULL,
    VALOR_RESIDENCIAL DECIMAL(8,2),
    VALOR_COMERCIAL DECIMAL(8,2),
    DATA_LIMITE_INICIAL TIMESTAMP NOT NULL,
    DATA_FINAL TIMESTAMP NOT NULL
)ENGINE=INNODB;