CREATE TABLE IF NOT EXISTS NM_NOTIFICACAO (
    ID BINARY(16) PRIMARY KEY NOT NULL,
    USUARIO_ID BINARY(16) NOT NULL,
    TENTATIVAS INTEGER,
    STATUS INTEGER NOT NULL DEFAULT 0,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ENVIO TIMESTAMP,
    CONSTRAINT FK_NOTIFICACAO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES NM_USUARIO(ID)
)ENGINE=INNODB;