CREATE TABLE IF NOT EXISTS NM_NOTIFICACAO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    USUARIO_ID BIGINT NOT NULL,
    TENTATIVAS INTEGER,
    STATUS INTEGER NOT NULL DEFAULT 0,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ENVIO TIMESTAMP,
    TIPO INTEGER,
    CONSTRAINT FK_NOTIFICACAO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES NM_USUARIO(ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;