CREATE TABLE NM_IMPORTACAO_CONDOMINIO (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NOME varchar(80) NOT NULL,
  TELEFONE varchar(20) NOT NULL,
  EMAIL varchar(100) DEFAULT NULL,
  DESCRICAO_UNIDADE varchar(60) NOT NULL,
  UNIDADE_ID binary(16) DEFAULT NULL,
  MSG_ERRO varchar(300) DEFAULT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;