CREATE TABLE NM_IMPORTACAO_CONDOMINIO (
  ID int NOT NULL AUTO_INCREMENT,
  NOME varchar(80) NOT NULL,
  TELEFONE varchar(20) NOT NULL,
  EMAIL varchar(100) DEFAULT NULL,
  DESCRICAO_UNIDADE varchar(60) NOT NULL,
  UNIDADE_ID binary(16) DEFAULT NULL,
  MSG_ERRO varchar(300) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB;