CREATE TABLE NM_LOG (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  MENSAGEM varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  DATA_HORA datetime DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;