CREATE TABLE NM_LOG (
  ID int NOT NULL AUTO_INCREMENT,
  MENSAGEM varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  DATA_HORA datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
) ENGINE=InnoDB;