CREATE TABLE NM_VALOR_NIVEL_COBRANCA (
  ID binary(16) PRIMARY KEY NOT NULL,
  LIMITE_INICIAL int NOT NULL,
  LIMITE_FINAL int NOT NULL,
  VALOR_RESIDENCIAL decimal(8,2) DEFAULT NULL,
  VALOR_COMERCIAL decimal(8,2) DEFAULT NULL,
  VALOR_FIXO decimal(8,2) DEFAULT NULL,
  DATA_INICIAL timestamp NOT NULL,
  DATA_FINAL timestamp NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;