CREATE TABLE NM_CONFIRMATION_TOKEN (
  ID BINARY(16) PRIMARY KEY NOT NULL,
  USUARIO_ID BINARY(16) NOT NULL,
  CREATE_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  EXPIRES_AT DATETIME NOT NULL,
  CONFIRMED_AT DATETIME,
  TOKEN BINARY(16) NOT NULL,
 CONSTRAINT FK_CONFIRMATION_TOKEN_USUARIO FOREIGN KEY(USUARIO_ID) REFERENCES NM_USUARIO(ID)
) ENGINE=InnoDB;