CREATE TABLE NM_CONFIRMATION_TOKEN (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  USUARIO_ID BIGINT NOT NULL,
  CREATE_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  EXPIRES_AT DATETIME NOT NULL,
  CONFIRMED_AT DATETIME,
  TOKEN INT(8) NOT NULL,
 CONSTRAINT FK_CONFIRMATION_TOKEN_USUARIO FOREIGN KEY(USUARIO_ID) REFERENCES NM_USUARIO(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;